apiVersion: apps/v1
kind: Deployment
metadata:
  name: $code_server_deployment
  labels:
    app: $code_server
spec:
  template:
    metadata:
      name: code_pod
      labels:
        app: $code_server
    spec:
      containers:
        - name: codeserver
          image: vinothmohan/code-server:latest
          ports:
            - containerPort: 8025
replicas: 3
selector:
  matchLabels:
    app: $code_server
