apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
  labels:
    app: code-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      name: code-server
      labels:
        app: code-server
    spec:
      containers:
        - name: codeserver
          image: vinothmohan/code-server:latest
          ports:
            - containerPort: 8025
